#!/usr/bin/env node
/**
 * \brief Read NPM package info and produce a Gentoo ebuild skeleton.
 *
 * This stupid^Wsimple program aimed to help me to write ebuilds for
 * NPM packages. [There is][neurogeek] a eclass for that I've found and
 * improve a little which helps a lot.
 *
 * \attention Review the log generated and pay attention to warnings!
 * This program far from good (yeah, just initial (naive) implementation).
 *
 * [neurogeek]: git://anongit.gentoo.org/dev/neurogeek.git
 */

var argv = require('argv');
var fs = require('fs');
var mkdirp = require('mkdirp');
var mustache = require('mustache');
var npm = require('npm');
var semver = require('semver');
var spdx = require('spdx');

// Declare program options
var options = {
    name: 'output-path'
  , short: 'o'
  , type: 'path'
  , description: 'Output path to write ebuilds hierarchy'
};

var args = argv.option(options).run();
// console.log("%j", args);

if (!args.targets.length)
{
    console.log('No package(s) given');
    process.exit(0);
}

/// \todo Avoid hardcode
var EBUILD_TEMPLATE = fs.readFileSync('./templates/ebuild.template');
var VERSION_MATCH_RE = /(\^|~|>|>=)?\s*([\w.]+)/;
var seen_packages = [];

/// Helper funtion to produce valid ebuild name from NPM pakcage name
function make_ebuild_name(npm_pkg_name)
{
    return npm_pkg_name.toLowerCase()
      .replace(new RegExp('[^a-z0-9\\-_]', 'g'), '-')
        // Fix weird cases
      .replace('-_', '-')
      ;
}

/// Helper function to render ebuild
function handle_package(info)
{
    // Transform dependencies into array and produce ebuilds for them
    // (to avoid second iteration later on same hash ;-)
    var dependencies = [];
    if (info.hasOwnProperty('dependencies'))
    {
        Object.keys(info.dependencies).forEach(
            function(key)
            {
                var version = null;
                var operation = '';

                var match = VERSION_MATCH_RE.exec(info.dependencies[key]);
                if (match)
                {
                    // Try to use semver parser to validate version
                    if (semver.valid(match[2]))
                    {
                        version = match[2];
                    }
                    else if (match[2].indexOf('x') != -1)
                    {
                        version = match[2].replace('x', '*');
                        // Prevent versions like '1.2.*' -- transform to '1.2*'...
                        version = version.slice(0, version.indexOf('*') + 1).replace('.*', '*');
                        operation = '=';
                        console.log('*** NOTE: Found wildcard version: %s -> %s', match[2], version);
                    }
                    else
                    {
                        // Last attempt to match not conforming version numbers
                        var last_attempt_match = /(\d+(.\d+(.\d+)?)?)/.exec(match[2]);
                        if (last_attempt_match)
                        {
                            version = last_attempt_match[1];
                            if (last_attempt_match[2] == undefined)
                            {
                                version += '*';
                                operation = '=';
                            }
                            if (last_attempt_match[2] != undefined && last_attempt_match[3] == undefined)
                            {
                                version += '*';
                                operation = '=';
                            }
                        }
                        else
                        {
                            console.log('*** ATTENTION: version parse error on "%s"', info.dependencies[key]);
                            version = null;
                        }
                    }
                    // Try to choose operation on dependency
                    if (operation === '' && version)
                    {
                        /// \todo Select proper operation
                        if (match[1] === '>=' || match[1] === '~' || match[1] === '^')
                        {
                            operation = '>=';
                        }
                        else if (version)
                        {
                            operation = '~';
                        }
                    }
                }

                // console.log('    %s %s %j', key, info.dependencies[key], version);
                dependencies.push({
                    name: make_ebuild_name(key)
                  , version: version
                  , op: operation
                  });
                // Produce ebuilds for dependencies
                produce_ebuilds(key);
            }
          );
    }

    // Transfrom binary files list into array
    var bin_files = [];
    var has_bin_files = false;
    if (info.hasOwnProperty('bin'))
    {
        Object.keys(info.bin).forEach(
            function(symlink_name)
            {
                bin_files.push({
                    symlink_name: symlink_name
                  , name: info.bin[symlink_name]
                  });
            }
          );
        has_bin_files = true;
    }

    var required_nodejs_version = '0.10';
    var required_nodejs_version_op = '>=';
    if (info.hasOwnProperty('engines'))
    {
        Object.keys(info.engines).forEach(
            function(key)
            {
                if (key == 'node')
                {
                    var match = VERSION_MATCH_RE.exec(info.engines[key]);
                    if (match)
                    {
                        var version = match[2];
                        if (semver.valid(version))
                        {
                            required_nodejs_version = version;

                            if (match[1] === '>=' || match[1] === '~' || match[1] === '^')
                                required_nodejs_version_op = '>=';
                            else
                                required_nodejs_version_op = '=';
                        }
                    }
                }
            }
          );
    }

    // NPM license may contain complex expression...
    console.log('info.license=%s', info.license);
    if (info.hasOwnProperty('license'))
    {
        try
        {
            var license_expression = spdx.parse(info.license);
            if (license_expression.hasOwnProperty('license'))
                license = license_expression.license;
            else
                license = 'Complicated';
        }
        catch (ex)
        {
            license = 'Unknown';
        }
    }
    else license = 'UNLICENSED';

    // Make sure package name would be valid
    var ebuild_name = make_ebuild_name(info.name);

    // Prepare data for rendering template
    var ebuild_data = {
        npm_module_name: (ebuild_name !== info.name) ? info.name : null
      , version: info.version
      , description: info.description.replace(/"/g, "'")
      , homepage: info.homepage
      , license: license
      , dependencies: dependencies
      , has_bin_files: has_bin_files
      , bin_files: bin_files
      , required_nodejs_version: required_nodejs_version
      , required_nodejs_version_op: required_nodejs_version_op
    };

    // Make some spam
    // console.log("%j", info);
    console.log("---[BEGIN %s-%s.ebuild data]---", ebuild_name, info.version);
    console.dir(ebuild_data, {colors: true});
    console.log("---[END %s-%s.ebuild data]---\n", ebuild_name, info.version);

    var ebuild_dir = (args.options['output-path'] ? args.options['output-path'] + '/' : './')
      + 'dev-nodejs/' + ebuild_name + '/';
    mkdirp(
        ebuild_dir
      , function(err)
        {
            var output = mustache.render(EBUILD_TEMPLATE.toString(), ebuild_data);
            fs.writeFile(ebuild_dir + ebuild_name + '-' + info.version + '.ebuild', output);
        }
      );

    var raw_json_dir = (args.options['output-path'] ? args.options['output-path'] + '/' : './')
      + 'packages-data/';
    mkdirp(
        raw_json_dir
      , function(err)
        {
            fs.writeFile(raw_json_dir + info.name + '-' + info.version + '.json', JSON.stringify(info, null, 2));
        }
      );
}

/// Retrieve package JSON data and produce ebuild for given name
function produce_ebuilds(package_name)
{
    if (seen_packages.indexOf(package_name) != -1)
    {
        console.log('*** NOTE: Skip %s package cuz already made/scheduled ebuild for it', package_name);
        return;
    }

    npm.load(
        function (er)
        {
            if (er)
                return handlError(er);

            npm.commands.view(
                [package_name]
              , true
              , function(er, data)
                {
                    if (er)
                        return commandFailed(er);
                    // command succeeded, and data might have some info
                    handle_package(data[Object.keys(data)[0]]);
                }
              );
        }
      );

    seen_packages.push(package_name);
}

// Iterate over requested package names and produce ebuilds
args.targets.forEach(produce_ebuilds);

// kate: hl javascript;
